apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: demo
spec:
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: test
        image: omerl/pod_kube_api_demo